version: '3.9'

services:
  postgres:
    image: postgres:16
    environment: 
      POSTGRES_USER:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DBNAME:
    ports:
      - target: 5432
        published: ${POSTGRES_PUBLISH_PORT:-5432}
        mode: host
    secrets:
      - postgres_password
    command: postgres -c max_connections=2048 -c shared_buffers=32GB -c work_mem=8GB -c max_wal_size=16GB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    shm_size: 16G
    tmpfs:
      - /shm_tmp:size=16G
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - "node.labels.${TONCENTER_ENV:?}.indexer-cpp.storage==true"
    networks:
      internal:
    logging:
      driver: local
      options:
        max-size: 4G

volumes:
  postgres_data:
    external: false

networks:
  internal:
    attachable: true
    external: false
    driver_opts:
      com.docker.network.driver.mtu: 1350

secrets:
  postgres_password:
    file: ${POSTGRES_PASSWORD_FILE:-private/postgres_password}
