x-index-pg-access: &index-pg-access
  POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
  POSTGRES_DB: ${POSTGRES_DB:-ion_index}

services:
  event-cache:
    image: redis:8-alpine
    networks:
      - internal
    command: redis-server --maxclients 40000
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  event-classifier:
    image: ice-blockchain/ion-indexer-classifier:v1.2.8
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      target: classifier
    depends_on:
      postgres:
        condition: service_healthy
      event-cache:
        condition: service_healthy
    secrets:
      - postgres_password
    command: --pool-size ${ION_INDEXER_WORKERS:-8} --prefetch-size 10000 --batch-size 1000
    environment: 
      <<: *index-pg-access
      ION_INDEXER_REDIS_DSN: redis://event-cache:6379
      ION_INDEXER_IS_TESTNET: ${ION_INDEXER_IS_TESTNET:-0}
    restart: unless-stopped
    networks:
      internal:

  index-api:
    image: ice-blockchain/ion-indexer-api:v1.2.8
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      target: index-api
    depends_on:
      postgres:
        condition: service_healthy
      run-migrations:
        condition: service_completed_successfully
    secrets:
      - postgres_password
    command: -prefork -threads ${ION_INDEXER_WORKERS:-1}
    ports:
      - target: 8081
        published: ${ION_INDEXER_API_PORT:-8081}
    environment:
      <<: *index-pg-access
      ION_ACCOUNT_EXCLUDED: ${ION_ACCOUNT_EXCLUDED}
      ION_INDEXER_API_ROOT_PATH: ${ION_INDEXER_API_ROOT_PATH:-/}
      ION_INDEXER_API_PORT: ${ION_INDEXER_API_PORT:-8081}
      ION_INDEXER_ION_HTTP_API_ENDPOINT: ${ION_INDEXER_ION_HTTP_API_ENDPOINT:-}
      ION_INDEXER_IS_TESTNET: ${ION_INDEXER_IS_TESTNET:-0}
      ION_INDEXER_IMGPROXY_BASEURL: ${ION_INDEXER_IMGPROXY_BASEURL:-}
    restart: unless-stopped
    networks:
      internal:

  run-migrations:
    image: ice-blockchain/ion-indexer-worker:v1.2.8
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      target: index-worker
    depends_on:
      postgres:
        condition: service_healthy
    secrets:
      - postgres_password
    environment: 
      <<: *index-pg-access
      ION_WORKER_BINARY: ion-index-postgres-migrate
    networks:
      internal:
    command: ion-index-postgres-migrate --pg postgresql://${POSTGRES_USER}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    restart: on-failure

  index-worker:
    image: ice-blockchain/ion-indexer-worker:v1.2.8
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      target: index-worker
    depends_on:
      postgres:
        condition: service_healthy
      run-migrations:
        condition: service_completed_successfully
    secrets:
      - postgres_password
    volumes:
      - ${ION_WORKER_DBROOT:-/var/ion-work/db}:/iondb:ro
      - ion_index_workdir:/ion_index_workdir
    environment:
      <<: *index-pg-access
      ION_WORKER_BINARY: ion-index-postgres
      ION_INDEXER_IS_TESTNET: ${ION_INDEXER_IS_TESTNET:-0}
    networks:
      internal:
    command: ion-index-postgres --pg postgresql://${POSTGRES_USER}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB} --db /iondb --working-dir /ion_index_workdir --from ${ION_WORKER_FROM:?} ${ION_WORKER_ADDITIONAL_ARGS:-}
    restart: unless-stopped

  postgres:
    image: postgres:17
    environment: 
      <<: *index-pg-access
    ports:
      - ${POSTGRES_PUBLISH_PORT:-5432}:5432
    secrets:
      - postgres_password
    command: postgres ${POSTGRES_ADDITIONAL_ARGS:-}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    shm_size: 2G
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      internal:
    logging:
      driver: local
      options:
        max-size: 4G

# additional: offchain metadata indexer
  metadata-fetcher:
    profiles: [metadata]
    image: ice-blockchain/ion-indexer-metadata-fetcher:v1.2.8
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      target: metadata-fetcher
    depends_on:
      postgres:
        condition: service_healthy
      run-migrations:
        condition: service_completed_successfully
    restart: unless-stopped
    secrets:
      - postgres_password
    networks:
      internal:
    environment:
      <<: *index-pg-access
    command: -imgproxy-salt ${IMGPROXY_SALT?} -imgproxy-key ${IMGPROXY_KEY?} -processes 8

  imgproxy:
    profiles: [metadata]
    image: ghcr.io/imgproxy/imgproxy:v3.29
    environment: 
      IMGPROXY_SALT: ${IMGPROXY_SALT?}
      IMGPROXY_KEY: ${IMGPROXY_KEY?}
      IMGPROXY_PRESETS: "small=rt:auto/w:128/h:128,medium=rt:auto/w:300/h:300,big=rt:auto/w:512/h:512"
      IMGPROXY_USER_AGENT:
    restart: unless-stopped
    ports:
      - ${IMGPROXY_PORT:-8201}:8080
    networks:
      internal:

# additional: API Emulate
  emulate-task-emulator:
    profiles: [emulate]
    image: ice-blockchain/ion-indexer-worker:v1.2.8
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000    
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      target: index-worker
    depends_on:
      emulate-redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      run-migrations:
        condition: service_completed_successfully
    networks:
      internal:
    environment:
      <<: *index-pg-access
      ION_INDEXER_EMULATE_REDIS_DSN: redis://emulate-redis:6379
      ION_WORKER_BINARY: ion-trace-task-emulator
      ION_INDEXER_IS_TESTNET: ${ION_INDEXER_IS_TESTNET:-0}
    command: --redis tcp://emulate-redis:6379 --db /iondb --working-dir /ion_emulate_workdir ${ION_EMULATE_ADDITIONAL_ARGS:-}
    secrets:
      - postgres_password
    volumes:
      - ${ION_WORKER_DBROOT:-/var/ion-work/db}:/iondb:ro
      - ion_emulate_workdir:/ion_emulate_workdir

  emulate-redis:
    profiles: [emulate]
    image: redis:8-alpine
    networks:
      internal:
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  emulate-event-classifier:
    profiles: [emulate]
    image: ice-blockchain/ion-indexer-classifier:v1.2.8
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      target: classifier
    depends_on:
      postgres:
        condition: service_healthy
      emulate-redis:
        condition: service_healthy
      emulate-task-emulator:
        condition: service_started
    secrets:
      - postgres_password
    command: --emulated-trace-tasks --emulated-traces-redis-channel classifierchannel
    environment:
      <<: *index-pg-access
      ION_INDEXER_REDIS_DSN: redis://emulate-redis:6379
      ION_INDEXER_IS_TESTNET: ${ION_INDEXER_IS_TESTNET:-0}
    restart: unless-stopped
    networks:
      internal:

  emulate-api:
    profiles: [emulate]
    image: ice-blockchain/ion-indexer-emulate-api:v1.2.8
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      target: emulate-api
    depends_on:
      postgres:
        condition: service_healthy
      run-migrations:
        condition: service_completed_successfully
    secrets:
      - postgres_password
    command: -prefork -redis emulate-redis:6379
    ports:
      - target: 8080
        published: ${ION_EMULATE_API_PORT:-8082}
    environment:
      <<: *index-pg-access
      ION_INDEXER_IS_TESTNET: ${ION_INDEXER_IS_TESTNET:-0}
      ION_INDEXER_IMGPROXY_BASEURL: ${ION_INDEXER_IMGPROXY_BASEURL:-}
    restart: unless-stopped
    networks:
      internal:

  metadata-cache:
    profiles: [ metadata ]
    image: ice-blockchain/ion-metadata-cache:v1.2.8
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      target: metadata-cache
    depends_on:
      postgres:
        condition: service_healthy
      run-migrations:
        condition: service_completed_successfully
    secrets:
      - postgres_password
    ports:
      - target: 8000
        published: ${ION_METADATA_CACHE_PORT:-18082}
    environment:
      <<: *index-pg-access
      ION_INDEXER_IS_TESTNET: ${ION_INDEXER_IS_TESTNET:-0}
      ION_METADATA_CACHE_PG_REPL: $ION_METADATA_CACHE_PG_REPL
      ION_METADATA_CACHE_REDIS: $ION_METADATA_CACHE_REDIS
    restart: unless-stopped
    networks:
      internal:

volumes:
  postgres_data:
    external: false
  ion_index_workdir:
    external: false
  ion_emulate_workdir:
    external: false

networks:
  internal:
    attachable: true
    external: false

secrets:
  postgres_password:
    file: ${POSTGRES_PASSWORD_FILE:-private/postgres_password}
